{"event": "verbose", "uuid": "7afbf3ff-9f63-476b-b1c2-d558bbb15168", "counter": 5, "stdout": "\u001b[0;31mThe error appears to be in '/Users/sanjanadas/fabfed_venv/lib/python3.10/site-packages/fabfed/provider/janus/ansible/roles/apt_installer/tasks/main.yml': line 2, column 3, but may\u001b[0m", "start_line": 4, "end_line": 5, "runner_ident": "33a1ada2-238e-415a-9227-9e8a91207f12", "created": "2025-01-17T20:27:55.804865"}