{"event": "verbose", "uuid": "f6380d5c-fda8-4cf6-be52-b3ee4b408ac1", "counter": 5, "stdout": "\u001b[0;31mThe error appears to be in '/Users/sanjanadas/fabfed_venv/lib/python3.10/site-packages/fabfed/provider/janus/ansible/roles/apt_installer/tasks/main.yml': line 2, column 3, but may\u001b[0m", "start_line": 4, "end_line": 5, "runner_ident": "2e5fd6a7-5261-47a8-8db1-d74e70fb0809", "created": "2025-01-17T20:27:56.361348"}